version: '3.8'


services:
  felix.api:
    image: ${DOCKER_REGISTRY-}felixapi
    container_name: felix_api
    build:
      context: .
      dockerfile: Felix.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=dbfelix;Username=felixpg;Password=passfelix"

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=felixpg
      - POSTGRES_PASSWORD=passfelix
      - POSTGRES_DB=dbfelix


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8081:80"
    depends_on:
      - postgres

